[package]
name = "omnisci-log-scraper"
version = "0.1.0"
authors = ["Alex Baden <alex.baden@mapd.com>", "Mike Hinchey <mike.hinchey@omnisci.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
regex = "1"
csv = "1.1.3"
clap = "2.33.1"
pager = "0.15.0"
colored = "1.9.3"
serde = { version = "1.0", features = ["derive"] }
