[package]
name = "omnisci-log-scraper"
version = "0.1.0"
edition = "2018"
authors = ["Alex Baden <alex.baden@mapd.com>",
           "Mike Hinchey <mike.hinchey@omnisci.com>"]
description = "Scrapes OmniSci DB logs for useful data"
license = "Apache-2.0"
# license-file = "LICENSE.md"
homepage = "https://omnisci.com/"
keywords = ["omnisci", "sql", "db", "database", "gpu", "log"]
categories = ["command-line-utilities"]
readme = "README.md"
repository = "https://github.com/omnisci/log-scraper"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
regex = "1"
csv = "1.1.3"
clap = "2.33.1"
pager = "0.15.0"
colored = "1.9.3"
serde = { version = "1.0", features = ["derive"] }
